### ISSUE TITLE
Add support for GameObjectContainer

### ISSUE THREAD

**Issue by gnunua** [RobotlegsJS/RobotlegsJS-Phaser#54]
## Expected Behavior

It would be great having mediators for Game Object Containers.

## Current Behavior

Managing all view behaviour only from scene mediators is not confottable. 

## Possible Solution

Folowwing the existing examples for `Robotlegs-Pixi` and ` Robotlegs-Phaser` implement appropriate functionality for `Phaser.GameObject.Container`

**Comment by tiagoschenkel** [comment]
Merge request #55 accepted.

Some suggestions for improvements are added to the `Changelog` but they can be handled in future updates.
