### ISSUE TITLE
Mediator is not created when scene stop/shutdown and then start again 

### ISSUE THREAD

**Issue by saqsun** [RobotlegsJS/RobotlegsJS-Phaser#78]
**Describe the bug**
After scene shutdown or stop if you try to start the same scene again, mediator will not be crated.

**To Reproduce**
1. Start the scene
2. Stop or shutdown the same scene
3. Then start the same scene again
4. See mediator will not be crated for the scene

**Expected behavior**
Mediator should be crated regardless of times the scene have been started.

**Comment by tiagoschenkel** [comment]
Solved by #79
